#!/usr/bin/env python3
import re
import operator
import csv

error_message= {}
list_error=[]
user_list={}
with open ('syslog.log') as file: # open file syslog.log
    for line in file.readlines():
        line.strip()
        pattern= r"ticky: ERROR ([\w\'?\s\w]*) \(.*\)" # filter pattern
        result= re.findall(pattern,line)
        if len(result) !=0 :
            list_error.append( result[0]) # list of mess
for error in list_error: # create list error message dictionary
    error_message[error]= error_message.get(error,0) +1
error_message=sorted(error_message.items(), key = operator.itemgetter(1),reverse= True)
with open('error_message.csv', 'w', newline='') as csv_error: # create csv file
    writer = csv.writer(csv_error, delimiter=',',quotechar='|', quoting=csv.QUOTE_MINIMAL)
    writer.writerow(["Error","Count"])
    writer.writerows(error_message)
#part2
user_count_info={}
user_count_error={}
info_list=[]
error_list=[]

error_pattern= r"ticky: ERROR [\w\'?\s\w]* \((.*)\)"
info_pattern= r"ticky: INFO [\w\'?\s\w]* \[\#\d*\] \((.*)\)"
with open ('syslog.log') as file: # open file syslog.log
    for line in file.readlines():
        line.strip()
        result_info= re.findall(info_pattern,line)
        result_error= re.findall(error_pattern,line)
        if len(result_info) != 0:
            info_list.append(result_info[0])
        if len(result_error) != 0:
            error_list.append(result_error[0])
for user in info_list: # create dictionary user info
    user_count_info[user]= user_count_info.get(user,0) +1
for user in error_list: # create dictionary user error
    user_count_error[user]= user_count_error.get(user,0) +1
# check to make sure 2 dict has total the same user
for user in user_count_error.keys():
    if user not in user_count_info:
        user_count_info[user]= 0
for user in user_count_info.keys():   
    if user not in user_count_error:
        user_count_error[user]= 0
# created a list contain username, info, error_list
list_final=[]
for user in sorted(user_count_info.keys()):
    dict_user={}
    dict_user["Username"]= user
    dict_user["INFO"]= user_count_info[user]
    dict_user["ERROR"]= user_count_error[user]
    list_final.append( dict_user)
with open('user_statistics.csv', 'w', newline='') as user_statistics : # create csv user_statistics file
    keys=["Username", "INFO", "ERROR"]
    writer = csv.DictWriter(user_statistics, fieldnames= keys)
    writer.writeheader()
    for i in (range(len(list_final))):
        writer.writerow(list_final[i])
with open ('error_message.csv', 'r') as file:
    for line in file.readlines():
        print(line)
with open ('user_statistics.csv', 'r') as file:
    for line in file.readlines():
        print(line)
